PRODUCT_NAME := twrp_AGo-32
PRODUCT_DEVICE := Pop 6 Pro
PRODUCT_BRAND := Tecno
PRODUCT_MODEL := Pop 6 Pro
PRODUCT_MANUFACTURER := TECNO

TARGET_VENDOR_PRODUCT_NAME := Tecno Pop 6 Pro
TARGET_VENDOR_DEVICE_NAME := Tecno Pop 6 Pro
