$(call inherit-product, $(SRC_TARGET_DIR)/product/full_base.mk)

PRODUCT_RELEASE_NAME := AGo_32

PRODUCT_NAME := twrp_AGo_32
PRODUCT_DEVICE := AGo_32
PRODUCT_BRAND := Tecno
PRODUCT_MODEL := Tecno Pop 6 Pro
PRODUCT_MANUFACTURER := TECNO
